Support children with bundle links, remove version pinnning (unused) [SE-2192]
labxchange/lx-pathway-plugin pull request #7
Opened 2020-03-31 22:43 UTC by bradenmacdonald

This updates the pathway plugin so that pathways can include XBlocks that use bundle links, such as the assignment XBlock. I found a way to do this while also making the code much cleaner and even somewhat more performant (reducing database queries using a per-request cache).

In order to do this, it was necessary to remove support for "freezing" pathway content at an older version, something we were no longer using anyways.

Should be completely backwards-compatible; existing pathway IDs won't change.

Test instructions:

1. Check out the latest version of https://github.com/edx/edx-platform/pull/23233
2. Run the following on your devstack:

```
make studio-shell
make -f /edx/src/lx-pathway-plugin/Makefile validate
```

2020-04-07 16:23 UTC, symbolist commented on lx_pathway_plugin/models.py
> +                    raise serializers.ValidationError("Pinning the version of pathway items is no longer supported.")
Hmm, I am not clear about this change. We do need to add support for specifying versions of xblocks.

2020-04-09 16:24 UTC, bradenmacdonald commented on lx_pathway_plugin/models.py
> +                    raise serializers.ValidationError("Pinning the version of pathway items is no longer supported.")
Just confirmed it's not needed for now.

2020-04-09 16:31 UTC, symbolist approved these changes
👍 (We have confirmed that freezing child xblocks is not needed.)

- [x] I tested this in the LX interface by creating and interacting with pathways with 2 layers of xblocks.
- [x] I read through the code
- [x] I checked for accessibility issues
- [x] Includes documentation

2020-04-28 06:45 UTC, ormsbee requested changes
Small request w.r.t. the request cache usage.

2020-04-28 06:45 UTC, ormsbee commented on lx_pathway_plugin/pathway_context.py
> +cache = RequestCache(namespace='lx-pathway-plugin')
Idiomatic usage of `RequestCache` is to instantiate at the local method level that you need it. It manages it as a thread local behind the scenes. I don't know if having a module-level reference to it like this can actually bite in some way (like memory leaks), but I'd feel more comfortable if you use it in the more common way.

2020-04-28 19:15 UTC, bradenmacdonald commented on lx_pathway_plugin/pathway_context.py
> +cache = RequestCache(namespace='lx-pathway-plugin')
> Idiomatic usage of `RequestCache` is to instantiate at the local method level 

No problem: https://github.com/open-craft/lx-pathway-plugin/compare/f56f9040df7c57094d6ef3577aafbb3104d26ea5..a2dee36e3a792d9b2af488326a695bd313ddb6d2

2020-04-28 19:25 UTC, merged